# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'ClientApp' do
  pod 'VendoredFramework', path: '../VendoredFrameworkPod'
end

target 'ClientAppUITestHost' do
  pod 'VendoredFramework', path: '../VendoredFrameworkPod'
end
